# Generated by Django 4.0.3 on 2022-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('strategy_id', models.CharField(db_column='strategy_id', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(db_column='user_id', max_length=30)),
                ('ss_id', models.IntegerField(db_column='ss_id')),
                ('ss_name', models.CharField(db_column='ss_name', max_length=50)),
                ('ss_price', models.DecimalField(blank=True, db_column='ss_price', decimal_places=0, max_digits=10, null=True)),
                ('transport', models.CharField(db_column='transport', max_length=4)),
                ('accommodation', models.CharField(db_column='accommodation', max_length=500)),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=255)),
                ('route', models.CharField(db_column='route', max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategy',
                'managed': False,
            },
        ),
    ]
