# Generated by Django 4.0.3 on 2022-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=16, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=8)),
                ('user_account', models.CharField(db_column='user_account', max_length=11)),
                ('user_password', models.CharField(db_column='user_password', max_length=16)),
                ('user_gender', models.IntegerField(blank=True, db_column='user_gender', null=True)),
                ('user_age', models.IntegerField(blank=True, db_column='user_age', null=True)),
                ('user_address', models.CharField(blank=True, db_column='user_address', max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
