# Generated by Django 4.0.4 on 2022-05-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('ss_id', models.IntegerField(db_column='ss_id', verbose_name='景区ID')),
                ('ss_name', models.CharField(db_column='ss_name', max_length=50, verbose_name='景区名称')),
                ('ss_image', models.CharField(blank=True, db_column='ss_image', max_length=50, null=True, verbose_name='景区样图')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '景区收藏',
                'verbose_name_plural': '景区收藏',
                'db_table': 'collect',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
