# Generated by Django 4.0.3 on 2022-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('ss_name', models.CharField(db_column='SS_Name', max_length=50)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=70, null=True)),
                ('ss_id', models.IntegerField(db_column='SS_ID', primary_key=True, serialize=False)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=5, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=10, null=True)),
                ('lng_wgs84', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('lat_wgs84', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ss_info', models.CharField(blank=True, db_column='SS_Info', max_length=500, null=True)),
                ('ss_image', models.CharField(blank=True, db_column='SS_Image', max_length=50, null=True)),
                ('ticket_price', models.DecimalField(blank=True, db_column='Ticket_Price', decimal_places=0, max_digits=10, null=True)),
                ('service_tele', models.CharField(blank=True, db_column='Service_Tele', max_length=15, null=True)),
            ],
            options={
                'db_table': 'scenic_spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SsAaaaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_name', models.CharField(db_column='SS_Name', max_length=50)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=70, null=True)),
                ('ss_id', models.IntegerField(db_column='SS_ID')),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=5, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=10, null=True)),
                ('lng_wgs84', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('lat_wgs84', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ss_info', models.CharField(blank=True, db_column='SS_Info', max_length=500, null=True)),
                ('ss_image', models.CharField(blank=True, db_column='SS_Image', max_length=50, null=True)),
                ('ticket_price', models.DecimalField(blank=True, db_column='Ticket_Price', decimal_places=0, max_digits=10, null=True)),
                ('service_tele', models.CharField(blank=True, db_column='Service_Tele', max_length=15, null=True)),
            ],
            options={
                'db_table': 'ss_aaaaa',
                'managed': False,
            },
        ),
    ]
