# Generated by Django 4.0.4 on 2022-05-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(db_column='comment_id', primary_key=True, serialize=False, verbose_name='评论ID')),
                ('user_id', models.CharField(db_column='user_id', max_length=30, verbose_name='用户ID')),
                ('ticket_id', models.IntegerField(db_column='ticket_id', verbose_name='景区ID')),
                ('imgurl', models.CharField(db_column='imageURL', max_length=200, verbose_name='景区图')),
                ('trans_value', models.DecimalField(db_column='trans_value', decimal_places=1, max_digits=3, verbose_name='交通评分')),
                ('service_value', models.DecimalField(db_column='service_value', decimal_places=1, max_digits=3, verbose_name='服务评分')),
                ('scene_value', models.DecimalField(db_column='scene_value', decimal_places=1, max_digits=3, verbose_name='景区评分')),
                ('total_value', models.DecimalField(db_column='total_value', decimal_places=1, max_digits=3, verbose_name='总评分')),
                ('message', models.CharField(blank=True, db_column='message', max_length=500, verbose_name='评价理由')),
                ('image_list', models.CharField(blank=True, db_column='image_list', max_length=500, null=True, verbose_name='评价图')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
    ]
