"""
Django settings for miniprogram_cms project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c+h1v4@t1@r6rn^tv#-=ofnxi_j#gcgw@6@s0nbv^c6mw2&^w!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cms',
    'rest_framework',
    'user',
    'strategy',
    'order',
    'comment',
]

SIMPLEUI_LOGO = 'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.alicdn.com%2Fimgextra%2F53%2F6c%2FTB1NkBdKVXXXXa1XVXXwu0bFXXX.png&refer=http%3A%2F%2Fimg.alicdn.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1653752326&t=2eb586930d0b2eb2998fbe9f25a981a2'
# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 隐藏首页的快捷操作和最近动作
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False

# 修改左侧菜单首页设置
SIMPLEUI_HOME_PAGE = 'https://siguso.com/'  # 指向页面
SIMPLEUI_HOME_TITLE = '思谷搜欢迎你！'  # 首页标题
SIMPLEUI_HOME_ICON = 'fa fa-code'  # 首页图标

# 设置右上角Home图标跳转链接，会以另外一个窗口打开
SIMPLEUI_INDEX = 'https://siguso.com/'

SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    # 'menu_display': ['用户管理', '景区管理', '攻略管理', '订单管理', '权限认证'],
    'menu_display': ['用户管理', '景区管理', '攻略管理', '订单管理', '评价管理'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [
        # {
        #     'app': 'auth',
        #     'name': '权限认证',
        #     'icon': 'fas fa-user-shield',
        #     'models': [
        #         {
        #             'name': '用户列表',
        #             'icon': 'fa fa-user',
        #             'url': 'auth/user/'
        #         },
        #         {
        #             'name': '用户组',
        #             'icon': 'fa fa-th-list',
        #             'url': 'auth/group/'
        #         }
        #     ]
        # },

        {
            'name': '用户管理',
            # 'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '用户列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/user/user/',
                    # 'icon': 'fa fa-tasks'
                },
            ]
        },

        {
            'name': '景区管理',
            # 'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '景区列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/cms/ssaaaaa/',
                    # 'icon': 'fa fa-tasks'
                },
            ]
        },

        {
            'name': '攻略管理',
            # 'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '攻略列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/strategy/strategy/',
                    # 'icon': 'fa fa-tasks'
                },
            ]
        },

        {
            'name': '订单管理',
            # 'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '订单列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/order/order/',
                    # 'icon': 'fa fa-tasks'
                },
            ]
        },

        {
            'name': '评价管理',
            # 'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '评价列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/comment/comment/',
                    # 'icon': 'fa fa-tasks'
                },
            ]
        },
    ]
}

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'miniprogram_cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'miniprogram_cms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default':
        {
            'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
            'NAME': 'test',  # 数据库名称
            'HOST': 'localhost',  # 数据库地址，本机 ip 地址 127.0.0.1
            'PORT': 3306,  # 端口
            'USER': 'root',  # 数据库用户名
            'PASSWORD': 'root',  # 数据库密码
        }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
# python manage.py collectstatic 时此行注释
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
# python manage.py collectstatic 时此行打开
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
