# Generated by Django 4.0.3 on 2022-04-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(db_column='order_id', max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='user_id', max_length=30)),
                ('commodity_list', models.CharField(db_column='commodity_list', max_length=500)),
                ('state_code', models.CharField(db_column='state_code', max_length=2)),
                ('total_price', models.DecimalField(db_column='total_price', decimal_places=0, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
